<?php

namespace Database\Seeders;

use App\Models\Tree;
use Illuminate\Database\Seeder;

class TreeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // El código para generar estos datos de prueba se sacaron de una tabla en Excel con el uso de fórmulas
        /*Tree::create(['id' => '1','id_padre' => null,'id_madre' => null,'nombres' => 'Rebeca Ester', 'apellido_padre' => 'Bazó','apellido_madre' => 'Rodríguez','sexo' => 'F','dia_nac' => '16','mes_nac' => '2','anho_nac' => '1976','lugar_nac' => 'Caracas / Distrito Capital','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '1','id_padre' => '2','id_madre' => '3','nombres' => 'Pedro José','nombres' => 'Pedro José','apellido_padre' => 'Bazó','apellido_madre' => 'Canelón','sexo' => 'M','dia_nac' => '6','mes_nac' => '12','anho_nac' => '1976','lugar_nac' => 'Caracas / Distrito Capital','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '2','id_padre' => '4','id_madre' => '5','nombres' => 'Carlos Alberto','nombres' => 'Carlos Alberto','apellido_padre' => 'Bazó','apellido_madre' => 'Gómez','sexo' => 'M','dia_nac' => '25','mes_nac' => '1','anho_nac' => '1947','lugar_nac' => 'Maracay / Aragua','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '20','mes_def' => '11','anho_def' => '2011','lugar_def' => 'Caracas / Distrito Capital','observaciones' => null]);
        Tree::create(['id' => '3','id_padre' => '6','id_madre' => '7','nombres' => 'Miriam Carolina','nombres' => 'Miriam Carolina','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'F','dia_nac' => '17','mes_nac' => '2','anho_nac' => '1950','lugar_nac' => 'Caracas / Distrito Capital','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '4','id_padre' => '8','id_madre' => '9','nombres' => 'Alejandro Enrique','nombres' => 'Alejandro Enrique','apellido_padre' => 'Bazó','apellido_madre' => 'Centeno','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1922','lugar_nac' => 'Cantaura / Anzoátegui ','dia_matr' => '24','mes_matr' => '2','anho_matr' => '1945','lugar_matr' => 'Caracas / Distrito Capital','dia_def' => '29','mes_def' => '7','anho_def' => '2008','lugar_def' => 'Caracas / Distrito Capital','observaciones' => null]);
        Tree::create(['id' => '5','id_padre' => '10','id_madre' => '11','nombres' => 'Elia María','nombres' => 'Elia María','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1919','lugar_nac' => 'Aragua de Barcelona / Anzoátegui ','dia_matr' => '24','mes_matr' => '2','anho_matr' => '1945','lugar_matr' => 'Caracas / Distrito Capital','dia_def' => '23','mes_def' => '11','anho_def' => '1989','lugar_def' => 'Caracas / Distrito Capital','observaciones' => null]);
        Tree::create(['id' => '6','id_padre' => '12','id_madre' => '13','nombres' => 'José María','nombres' => 'José María','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'M','dia_nac' => '31','mes_nac' => '5','anho_nac' => '1913','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '7','id_padre' => '14','id_madre' => '15','nombres' => 'Luisa Margarita','nombres' => 'Luisa Margarita','apellido_padre' => 'Hernández','apellido_madre' => 'Núñez','sexo' => 'F','dia_nac' => '20','mes_nac' => '11','anho_nac' => '1922','lugar_nac' => 'Santa Maria de Ipire / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '21','mes_def' => '8','anho_def' => '2008','lugar_def' => 'Caracas / Distrito Capital','observaciones' => 'En el acta de defunción se su padre aparace como Luisa Margot.']);
        Tree::create(['id' => '8','id_padre' => null,'id_madre' => null,'nombres' => 'Alejandro','nombres' => 'Alejandro','apellido_padre' => 'Bazó','apellido_madre' => 'Barolleta','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1895','lugar_nac' => 'Cantaura / Anzoátegui ','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '9','id_padre' => null,'id_madre' => null,'nombres' => 'Clara Elena','nombres' => 'Clara Elena','apellido_padre' => 'Centeno','apellido_madre' => 'Gil','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1897','lugar_nac' => 'Cantaura / Anzoátegui ','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '10','id_padre' => '24','id_madre' => '25','nombres' => 'Romualdo','nombres' => 'Romualdo','apellido_padre' => 'Gómez','apellido_madre' => 'Iragorri','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1862','lugar_nac' => 'Aragua de Barcelona / Anzoátegui ','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '6','mes_def' => '12','anho_def' => '1960','lugar_def' => 'Caracas / Distrito Capital','observaciones' => null]);
        Tree::create(['id' => '11','id_padre' => null,'id_madre' => null,'nombres' => 'Leonarda','nombres' => 'Leonarda','apellido_padre' => 'López','apellido_madre' => 'Méndez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1883','lugar_nac' => 'Aragua de Barcelona / Anzoátegui ','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '12','id_padre' => '16','id_madre' => '17','nombres' => 'José María','nombres' => 'José María','apellido_padre' => 'Canelón','apellido_madre' => 'Pérez','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1875','lugar_nac' => 'Puerto Cabello / Carabobo','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '13','id_padre' => '18','id_madre' => '19','nombres' => 'Luisa Dolores','nombres' => 'Luisa Dolores','apellido_padre' => 'Bustamante','apellido_madre' => 'Martínez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1878','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '28','mes_def' => '3','anho_def' => '1961','lugar_def' => 'Baruta / Miranda','observaciones' => null]);
        Tree::create(['id' => '14','id_padre' => '20','id_madre' => '21','nombres' => 'Luis Rafael','nombres' => 'Luis Rafael','apellido_padre' => 'Hernández','apellido_madre' => 'Barrios','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1895','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '18','mes_def' => '8','anho_def' => '1976','lugar_def' => 'Municipio Crespo / Aragua','observaciones' => null]);
        Tree::create(['id' => '15','id_padre' => '22','id_madre' => '23','nombres' => 'Adela','nombres' => 'Adela','apellido_padre' => 'Núñez','apellido_madre' => 'Ruiz','sexo' => 'F','dia_nac' => '31','mes_nac' => '5','anho_nac' => '1897','lugar_nac' => 'El Chaparro / Anzoátegui','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '16','id_padre' => null,'id_madre' => null,'nombres' => 'Pablo','nombres' => 'Pablo','apellido_padre' => 'Canelón','apellido_madre' => 'Navarro','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1840','lugar_nac' => 'Puerto Cabello / Carabobo','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '17','id_padre' => null,'id_madre' => null,'nombres' => 'Críspula','nombres' => 'Críspula','apellido_padre' => 'Pérez','apellido_madre' => 'Gorrión','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1845','lugar_nac' => 'Puerto Cabello / Carabobo','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '18','id_padre' => '50','id_madre' => '51','nombres' => 'José María','nombres' => 'José María','apellido_padre' => 'Bustamante','apellido_madre' => 'Zerpa','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1853','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => '8','mes_def' => '3','anho_def' => '1887','lugar_def' => 'Valle de La Pascua / Guárico','observaciones' => null]);
        Tree::create(['id' => '19','id_padre' => null,'id_madre' => null,'nombres' => 'Francisca Antonia','nombres' => 'Francisca Antonia','apellido_padre' => 'Martínez','apellido_madre' => 'Baduel','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1856','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '20','id_padre' => null,'id_madre' => null,'nombres' => 'Santos','nombres' => 'Santos','apellido_padre' => 'Hernández','apellido_madre' => 'Ochoa','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1870','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '21','id_padre' => null,'id_madre' => null,'nombres' => 'Julia','nombres' => 'Julia','apellido_padre' => 'Barrios','apellido_madre' => 'De Armas','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1875','lugar_nac' => 'Valle de La Pascua / Guárico','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '22','id_padre' => null,'id_madre' => null,'nombres' => 'Sancho','nombres' => 'Sancho','apellido_padre' => 'Núñez','apellido_madre' => 'Guzmán','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1867','lugar_nac' => 'El Chaparro / Anzoátegui','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '23','id_padre' => null,'id_madre' => null,'nombres' => 'María de Jesús','nombres' => 'María de Jesús','apellido_padre' => 'Ruiz','apellido_madre' => 'Silva','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => '1877','lugar_nac' => 'El Chaparro / Anzoátegui','dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '24','id_padre' => null,'id_madre' => null,'nombres' => 'José María','nombres' => 'José María','apellido_padre' => 'Gómez','apellido_madre' => 'Torres','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '25','id_padre' => null,'id_madre' => null,'nombres' => 'Encarnación','nombres' => 'Encarnación','apellido_padre' => 'Pimentel','apellido_madre' => 'Gómez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '26','id_padre' => '10','id_madre' => '11','nombres' => 'María','nombres' => 'María','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '27','id_padre' => '10','id_madre' => '11','nombres' => 'Carmen','nombres' => 'Carmen','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '28','id_padre' => '10','id_madre' => '11','nombres' => 'Romualdo','nombres' => 'Romualdo','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '29','id_padre' => '10','id_madre' => null,'nombres' => 'Lismes','nombres' => 'Lismes','apellido_padre' => 'Gómez','apellido_madre' => 'Palmar','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '30','id_padre' => '10','id_madre' => null,'nombres' => 'Leopardo','nombres' => 'Leopardo','apellido_padre' => 'Gómez','apellido_madre' => 'Rodríguez','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '31','id_padre' => '10','id_madre' => null,'nombres' => 'Delfin','nombres' => 'Delfin','apellido_padre' => 'Gómez','apellido_madre' => 'Rodríguez','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '32','id_padre' => '10','id_madre' => '11','nombres' => 'Luis','nombres' => 'Luis','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '33','id_padre' => '10','id_madre' => '11','nombres' => 'Barbaray','nombres' => 'Barbaray','apellido_padre' => 'Gómez','apellido_madre' => 'López','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '34','id_padre' => '6','id_madre' => '7','nombres' => 'José María','nombres' => 'José María','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '35','id_padre' => '6','id_madre' => '7','nombres' => 'Luis Cristian','nombres' => 'Luis Cristian','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '36','id_padre' => '6','id_madre' => '7','nombres' => 'Carmen Adriana','nombres' => 'Carmen Adriana','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '37','id_padre' => '6','id_madre' => '7','nombres' => 'Juan Carlos','nombres' => 'Juan Carlos','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '38','id_padre' => '6','id_madre' => '7','nombres' => 'María Margarita','nombres' => 'María Margarita','apellido_padre' => 'Canelón','apellido_madre' => 'Hernández','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '39','id_padre' => '12','id_madre' => '13','nombres' => 'Carmen','nombres' => 'Carmen','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '40','id_padre' => '12','id_madre' => '13','nombres' => 'Ana','nombres' => 'Ana','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '41','id_padre' => '12','id_madre' => '13','nombres' => 'Crispula','nombres' => 'Crispula','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '42','id_padre' => '12','id_madre' => '13','nombres' => 'José Luis','nombres' => 'José Luis','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '43','id_padre' => '12','id_madre' => '13','nombres' => 'Pablo','nombres' => 'Pablo','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '44','id_padre' => '12','id_madre' => '13','nombres' => 'Francisco','nombres' => 'Francisco','apellido_padre' => 'Canelón','apellido_madre' => 'Bustamante','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '45','id_padre' => '14','id_madre' => '15','nombres' => 'Julia','nombres' => 'Julia','apellido_padre' => 'Hernández','apellido_madre' => 'Núñez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '46','id_padre' => '14','id_madre' => '15','nombres' => 'Adelaida','nombres' => 'Adelaida','apellido_padre' => 'Hernández','apellido_madre' => 'Núñez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '47','id_padre' => '14','id_madre' => '15','nombres' => 'Carlos Enrique','nombres' => 'Carlos Enrique','apellido_padre' => 'Hernández','apellido_madre' => 'Núñez','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '48','id_padre' => '2','id_madre' => '3','nombres' => 'Luis Carlos','nombres' => 'Luis Carlos','apellido_padre' => 'Bazó','apellido_madre' => 'Canelón','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '49','id_padre' => '2','id_madre' => '3','nombres' => 'Marian','nombres' => 'Marian','apellido_padre' => 'Bazó','apellido_madre' => 'Canelón','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '50','id_padre' => null,'id_madre' => null,'nombres' => 'Pedro Jesús','nombres' => 'Pedro Jesús','apellido_padre' => 'Bustamante','apellido_madre' => 'Buros','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '51','id_padre' => null,'id_madre' => null,'nombres' => 'María Manuela','nombres' => 'María Manuela','apellido_padre' => 'Zerpa','apellido_madre' => 'Fernández','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '52','id_padre' => '4','id_madre' => '5','nombres' => 'Roberto José','nombres' => 'Roberto José','apellido_padre' => 'Bazó','apellido_madre' => 'Gómez','sexo' => 'M','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]);
        Tree::create(['id' => '53','id_padre' => '4','id_madre' => '5','nombres' => 'Josefina','nombres' => 'Josefina','apellido_padre' => 'Bazó','apellido_madre' => 'Gómez','sexo' => 'F','dia_nac' => null,'mes_nac' => null,'anho_nac' => null,'lugar_nac' => null,'dia_matr' => null,'mes_matr' => null,'anho_matr' => null,'lugar_matr' => null,'dia_def' => null,'mes_def' => null,'anho_def' => null,'lugar_def' => null,'observaciones' => null]); */
    }
}
